swagger: '2.0'
info:
  title: My API
  version: 1.0.0

paths:
  /users:
    get:
      summary: Get a list of users
      operationId: getUsers
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/definitions/User'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/User'

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      email:
        type: string